# Generated by Django 4.1.7 on 2023-02-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, default=None)),
                ('priority', models.IntegerField(blank=True, choices=[(0, 'Звичайне'), (1, 'Помітне'), (2, 'Термінове')], default=0)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('tags', models.ManyToManyField(blank=True, to='app.tagmodel')),
            ],
        ),
    ]
